name: Integration

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker build and push
        run: |
          docker build -t app .
          echo ${{ secrets.DOCKER_SECRET }} | docker login -u costigator --password-stdin
          docker tag app costigator/sonos_volume_monitor
          docker push costigator/sonos_volume_monitor
  
